version: 0.0
os: linux
files:
- source: "server.js"
  destination: "/home/ec2-user/app/"
- source: "init_data"
  destination: "/home/ec2-user/app/init_data/"
- source: "scripts"
  destination: "/home/ec2-user/app/scripts/"
- source: "views"
  destination: "/home/ec2-user/app/views/"
- source: "resources"
  destination: "/home/ec2-user/app/resources/"
- source: "package.json"
  destination: "/home/ec2-user/app/" 
- source: "package-lock.json"
  destination: "/home/ec2-user/app/"
- source: "node_modules"
  destination: "/home/ec2-user/app/node_modules/"
hooks:
  AfterInstall:
  - location: "scripts/setup_psql.sh"
    timeout: 300
    runas: root
  - location: "scripts/setup_httpd.sh"
    timeout: 300
    runas: root   
  ApplicationStart:
  - location: "scripts/start_script.sh"
    timeout: 300
    runas: root   
  ApplicationStop:
  - location: "scripts/stop_script.sh"
    timeout: 300
    runas: root   